### ISSUE TITLE
mouseemulation.exe is a malware

### ISSUE THREAD

**Issue by momala454** [TrueOpenVR/TrueOpenVR-Core#7]
this file is included on the portable zip 

https://www.virustotal.com/gui/file/dba88066394011d3df72abb99c35ed907d2a579ac8518a701463a9b07e79a6cf/detection

**Comment by r57zone** [comment]
Antiviruses, whose names I read for the first time. A good antivirus will not find any viruses there, because they are not there. 

The source code is [available to everyone](https://github.com/TrueOpenVR/TrueOpenVR-Tools/tree/master/MouseEmulation).

I will not delete anything because it is not a virus.

I do not think that you can trust antiviruses with strange names that are unclear by anyone.

**Comment by momala454** [comment]
it's not just 1 or 2 antivirus, it's 28. Should i trust 28 antivirus or someone from the internet ?

i don't have the knowledge to compile the source or analyse the source to know if it's safe

> I do not think that you can trust antiviruses with strange names that are unclear by anyone.

avast, avg, microsoft, mcafee are all "antiviruses with strange names" ?

**Comment by r57zone** [comment]
Of these antiviruses, I think that you can only trust Microsoft antivirus. In this situation, I think a false positive occurs, because Mouse Emulation is a utility for moving the cursor, it is necessary to play old games, in stereo 3D and change the view with the mouse and gyroscope (mouse emulation).

I think some viruses or trojans control the cursor, so antiviruses suggest that it is also a virus, but it is not.

If you play Half Life Alyx non VR, then this utility is not necessary and you can not use it.

You can also compile the sources using Microsoft Visual Studio 2017 and you will get the same result in virus total.

**Comment by epaga** [comment]
Just as a heads up, Polygon(!) almost wrote a story about this project, but then stopped because it triggered their virus check.

I HIGHLY recommend at least offering a stripped down version without the mouse emulation exe (or whatever is causing the virus false alarm). It explains why this amazing project has less than 100 stars.

Sometimes it's minor things that hold you back!

**Comment by r57zone** [comment]
I removed this app from archive, thanks for reminder. It's probably best to place it separately in [Tools](https://github.com/TrueOpenVR/TrueOpenVR-Tools/releases/).

I wrote to Avast, AVG and Microsoft to they manually test the utility. I think they should fix it.

If you write a story, please send me a link, thank you.

**Comment by epaga** [comment]
Awesome, man - and to be clear, it wouldn't be me writing the story, I'm just the author of SmoothTrack. https://inflightassistant.com/smoothtrack :) They were thinking of reporting on the fact that you can get head tracking in Star Wars: Squadrons with TrueOpenVR. See https://www.youtube.com/watch?v=Qjn6bgNTDNc&feature=youtu.be (which itself was inspired by ChoboN00b's tutorial on TrueOpenVR https://www.youtube.com/watch?v=_M4tHd7rpl8)

After your quick response of removing that file, the Polygon reporter I was in touch with said it's back in the queue for early next week. We'll see if they get the setup working and if so I'll send you the link once they post an article!

**Comment by epaga** [comment]
Just pinged the reporter and he said he's been re-tasked with a different bigger piece for the next few weeks so it's been put on hold for now unfortunately. :(
